language: node_js
node_js:
  - '16'
  - '8'
script:
  - npm run test
  - npm run build
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: npm
  email: "emish89@yahoo.it"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
install:
  - npm install -g codecov
script:
  - codecov
